name: first-workflow
on: push
jobs:
  log-greeting:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'helloo!'"
      - run: "echo 'how are you?'"
  log-date:
    runs-on: ubuntu-latest
    steps:
      - run: "date"
